package com.CollectionServer.DataAnalysis;

import jakarta.persistence.*;

import java.util.Date;

import java.util.Map;

@Entity
public class AnalysisJob 
{
	public enum JobStatus
	{
		SUBMITTED,
		RUNNING,
		COMPLETED,
		FAILED;
	}
	
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	public Integer Id;
	
	@Transient
	public AnalysisMethod analysisMethod;
	
	//Maps data point ID's to cluster ID's generated by the clustering algrorithm
	@ElementCollection
	public Map<Integer, Integer> clusters;
	
	public Date timeStarted;
	
	public Date timeFinished;
		
	public AnalysisMethod.AnalysisType analysisType;
	
	public JobStatus jobStatus;
	
	public AnalysisJob(AnalysisMethod analysisMethod)
	{
		this.analysisMethod = analysisMethod;
		analysisType = analysisMethod.analysisType;
		jobStatus = JobStatus.SUBMITTED;
		analysisMethod.parentJob = this;
	}
	
	public void startJob()
	{
		if(jobStatus == JobStatus.SUBMITTED)
		{
			//Start running analysisMethod
			analysisMethod.start();
		}
	}
}
